### ISSUE TITLE
Problem when you ask 1994-1995 SINASC data

### ISSUE THREAD

**Issue by igorfosp** [rfsaldanha/microdatasus#10]
Hi Rafael, how are you? Could you fix an issue on the current state of your package?

When I download SINASC data from 1994-1995, ti gives an error because your package is searching in the wrong FTP directory. The directory for 94-95 data is:

ftp://ftp.datasus.gov.br/dissemin/publicos/SINASC/1994_1995/Dados/DNRES/

Thank you so much. Your package is awesome.

**Comment by rfsaldanha** [comment]
Yes, indeed this occurs in several health information systems. The files are in different folders and the merge files process must handle different columns. It is on my list of priorities for the package.

**Comment by rfsaldanha** [comment]
The last update of the package (2.0) allows the download of older data and also of preliminar data.
