### ISSUE TITLE
Problema de Instalacão 

### ISSUE THREAD

**Issue by Wensko** [rfsaldanha/microdatasus#100]
Fala Rafael, beleza? To com um erro na instalação também, mas diferente do último issue aberto. Estou usando Windows 11.  Quando rodo na sessão usando R 4.2.1 tenho o seguinte erro: 

remotes::install_github("rfsaldanha/microdatasus")
Using GitHub PAT from the git credential store.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 53/60
  Rate limit reset at: 2024-04-04 14:52:04 UTC

Quando rodo na sessão 4.3.3 tenho o erro:

> remotes::install_github("rfsaldanha/microdatasus")
Using GitHub PAT from the git credential store.
Error: Failed to install 'unknown package' from GitHub:
  cannot open URL 'https://api.github.com/repos/rfsaldanha/microdatasus/contents/DESCRIPTION?ref=HEAD'

**Comment by rfsaldanha** [comment]
Olá Wensko,

Esse erro parece estar relacionado as suas chaves de acesso ao GitHub. De, qualquer forma, tente algumas alternativas como:

```r
devtools::install_github("rfsaldanha/microdatasus")
pak::pkg_install("rfsaldanha/microdatasus")
```

**Comment by rfsaldanha** [comment]
Tranquilo, sem problemas. Boa pesquisa para você!
