### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by hhmacedo** [rfsaldanha/microdatasus#103]
Esse link aqui está quebrado:

https://github.com/rfsaldanha/microdatasus/blob/74189fa722f28553db1e3ef708b2dd6ee23f4a2f/CITATION.cff#L17

Talvez seja melhor usar o do DOI (https://doi.org/10.1590/0102-311X00032419)?

**Comment by rfsaldanha** [comment]
Opa! Obrigado por avisar.
