### ISSUE TITLE
erro:  It appears that DataSUS FTP is down or not reachable.

### ISSUE THREAD

**Issue by medydcampos** [rfsaldanha/microdatasus#104]
Olá, estou tentando acessar a base de microdados do DataSUS com esse código:

install.packages("devtools")
devtools::install_github('rfsaldanha/microdatasus')
library(microdatasus)

data = fetch_datasus(year_start = 2000,
                     year_end = 2023, 
                     uf = "all",
                     information_system = "SINASC")

e estou recebendo esse erro:
ℹ Your local Internet connection seems to be ok.
! It appears that DataSUS FTP is down or not reachable.

O Chat GPT 4 afirma que esse erro é um problema de servidor e fala que é recomendado que eu tente mais tarde. Mas também pode ser algo relacionado ao pacote que não está atualizado, apesar de eu ter baixado ele no dia de hoje e ter solicitado todas as atualizações do pacote no momento de instalação. 
Alguém pode me explicar melhor o que está acontecendo? Eu sou nova no mundo da programação, tentando decifrar os códigos rsrsr obrigada!

**Comment by rfsaldanha** [comment]
Olá! Essa mensagem aparece quando você não tem Internet ou não está conseguindo acessar o servidor de arquivos FTP do DataSUS. Esse segundo caso pode acontecer se o servidor estiver em manutenção ou você se você tentar acessar de fora do Brasil. O acesso a partir de alguns países funciona, e de outros não... é uma configuração do DataSUS e não do pacote.

Você pode verificar também o problema de conexão abrindo esse endereço:

https://datasus.saude.gov.br/transferencia-de-arquivos/

E tentar baixar algum arquivo manualmente por lá. Se você não conseguir, provavelmente você está acessando o DataSUS à partir de algum lugar que não funciona.

Para contornar isso, sugiro habilitar uma VPN antes de tentar o download dos dados. Me diga aqui depois se deu certo!

**Comment by medydcampos** [comment]
Oi Rafael, muito obrigada pela resposta rápida.

Sim, não estou no Brasil, estou em Londres fazendo meu mestrado. Agora faz mais sentido.
Eu consegui extrair manualmente pelo link que você me enviou! Muito obrigada.
Sinto que a depender do desenrolar da minha tese, seria muito mão na roda usar esse pacote. Vou tentar a dica do VPN.

Abraços.

**Comment by rfsaldanha** [comment]
Ok. Qualquer coisa, pode avisar aqui.
