### ISSUE TITLE
PROC_REA e PROC_SOLIC

### ISSUE THREAD

**Issue by andventura** [rfsaldanha/microdatasus#106]
Quando se utiliza information_system = "SIA-PA" na função "fetch_datasus", não é possível adcionar as variáveis: PROC_REA e PROC_SOLIC referentes aos procedimentos realizados e solicitados, respectivamente. Ainda em fase de implementação? Ou tais variáveis são obtidas de outra forma através do pacote microdatasus?

**Comment by rfsaldanha** [comment]
Olá! Nos dados do SIA-PA (Sistema de Informações Ambulatoriais), os campos PROC_REA e PROC_SOLIC não existem. Os mais parecidos seriam PA_QTDPRO (quantidade produzida) e PA_QTDAPR (quantidade aprovada). Este documento apresenta o dicionário de dados completo do SIA-PA: ftp://ftp.datasus.gov.br/dissemin/publicos/SIASUS/200801_/Doc/Informe_Tecnico_SIASUS_2019_07.pdf

Mas esses campos (PROC_REA e PROC_SOLIC) estão presentes no Sistema de Informações Hospitalares (SIH). Você precisa trabalhar com Produção Ambulatorial (no SIA) ou Autorizações de Internações Hospitalares (no SIH)?

**Comment by andventura** [comment]
Obrigado, confundi SIA com SIH.

**Comment by rfsaldanha** [comment]
Ok! Se precisar de alguma ajuda, pode avisar.
