### ISSUE TITLE
Acesso ao dados do SISCAN

### ISSUE THREAD

**Issue by dtiezzi** [rfsaldanha/microdatasus#11]
Rafael, parabéns pelo desenvolvimente desta aplicação. É de grande utilidade.

Tenho um dúvida quanto ao acesso aos bancos de dados. É possível acessar os dados do SISCAN  (colo do útero e mama)?

**Comment by rfsaldanha** [comment]
Olá! Se os dados estiverem disponíveis no DataSUS, podemos incluir eles no pacote. Você sabe se os micro dados estão disponíveis?

**Comment by dtiezzi** [comment]
Eu não consegui acessar. Mas no fim de semana passado eu participei de um Datathon onde os organizadores disponibilizaram os dados no Google Cloud Platform. Mas os dados já estavam pre processados. Vou dar mais uma olhada.

**Comment by rfsaldanha** [comment]
Muito bom! Você chegou a pegar algum contato? Dependendo eu posso enviar uma mensagem para eles.
