### ISSUE TITLE
Erro no download do pacote microdatasus

### ISSUE THREAD

**Issue by migdep** [rfsaldanha/microdatasus#114]
Bom dia, espero que estejam bem!"

O download do pacote microdatasus está dando erro (ver linhas a seguir):

> remotes::install_github("rfsaldanha/microdatasus")
Downloading GitHub repo rfsaldanha/microdatasus@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/rfsaldanha/microdatasus/tarball/HEAD' failed

Como proceder?

**Comment by rfsaldanha** [comment]
Olá! Testei agora e funcionou comigo. Você pode tentar instalar diretamente do CRAN.

```r
install.packages("microdatasus")
```
Ou dessa outra forma:

```r
pak::pkg_install("rfsaldanha/microdatasus")
```

**Comment by migdep** [comment]
Testei os dois modos e deu erro:

> pak::pkg_install("rfsaldanha/microdatasus")
Error in loadNamespace(x) : there is no package called ‘pak’
In addition: Warning messages:
1: In grep("^[^#].*", lines, value = TRUE) :
  unable to translate 't<fc>' to a wide string
2: In grep("^[^#].*", lines, value = TRUE) : input string 2 is invalid
3: In read.table(path, encoding = encoding, header = header, sep = sep,  :
  line 1 appears to contain embedded nulls
4: In read.table(path, encoding = encoding, header = header, sep = sep,  :
  line 2 appears to contain embedded nulls
5: In read.table(path, encoding = encoding, header = header, sep = sep,  :
  incomplete final line found by readTableHeader on 'C:/Users/miguel.andino/Desktop/Miguel_NEP/Microdatasus/inst/files/sids.dbc'
> library(microdatasus)
Error in library(microdatasus) : 
  there is no package called ‘microdatasus’
> install.packages("microdatasus")
Warning in install.packages :
  package ‘microdatasus’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by rfsaldanha** [comment]
Você precisa instalar o pacote `pak`

```r
install.packages("pak")
``` 
e depois executar

```r
pak::pkg_install("rfsaldanha/microdatasus")
```

**Comment by migdep** [comment]
Está funcionando, muito obrigado!
