### ISSUE TITLE
compatível com R 4.4.*?

### ISSUE THREAD

**Issue by raquelvl** [rfsaldanha/microdatasus#119]
Tive o seguinte erro tentando instalar o pacote:
Warning in install.packages :
  package ‘microdatasus’ is not available for this version of R

meu R é versão 4.4.0.

**Comment by rfsaldanha** [comment]
Olá! Esta mensagem está aparecendo pois o pacote foi removido do CRAN devido a uma dependência. De qualquer modo, você pode instalar o pacote na versão de desenvolvimento com o seguinte comando:

```{r}
# install.packages("remotes")
remotes::install_github("rfsaldanha/microdatasus")
```

Me avise se tiver algum problema.
