### ISSUE TITLE
CNES: endereço do estabelecimento indisponível

### ISSUE THREAD

**Issue by Danhisco** [rfsaldanha/microdatasus#120]
Olá,
Espero que estejam bem.
Busco o endereço de hospitais para fazer a geocodificação. Entendo que deveria usar: information_system = "CNES-DC" ou "CNES-ST". 
Acessei todas as opções de CNES, em nenhuma existe informação sobre o endereço preenchido, sempre está 0 ou NA. 
Alguem poderia me orientar, por favor?
Obrigado,
Danilo

**Comment by rfsaldanha** [comment]
Olá! De fato, os arquivos do CNES disponibilizados pelo DataSUS não tem os dados de endereçamento. Mas esta base do  Ministério da Saúde contêm os estabelevimentos georreferenciados.

[](https://opendatasus.saude.gov.br/dataset/cnes-cadastro-nacional-de-estabelecimentos-de-saude)
