### ISSUE TITLE
Pacote não está instalando no R 4.4.1

### ISSUE THREAD

**Issue by richila** [rfsaldanha/microdatasus#121]
Bom dia, recentemente atualizei minha versão do R e o pacote do micro datasus não está mais abrindo. Tentei a reinstalação usando: 
install.packages("remotes")
remotes::install_github("rfsaldanha/microdatasus")

Porém, não consegui fazer a instalação. 
![image](https://github.com/user-attachments/assets/7c9171e1-c424-4644-8c32-a0d94b9c9099)

**Comment by csthiago** [comment]
Você precisa instalar o Rtools para poder compilar o read.dbc (depencia do pacote):
https://cran.r-project.org/bin/windows/Rtools/

**Comment by rfsaldanha** [comment]
Uma outra alternativa é instalar o pacote `read.dbc` já compilado que foi arquivado

```r
install.packages("read.dbc", repos = "https://packagemanager.posit.co/cran/2024-07-05")
```

e depois instalar o `microdatasus`
