### ISSUE TITLE
Problemas ao trazer info de SIA-AM

### ISSUE THREAD

**Issue by pharguz** [rfsaldanha/microdatasus#122]
Boa noite! Parabéns pelo excelente trabalho, fico feliz pela solução implementada.

Estou entando executar este comando
>dados <- fetch_datasus(year_start = 2011, year_end = 2013, uf="SP", information_system = "SIA-AM")

No entanto, ele  me traz este erro. 
>"Error in charToDate(x) : 
  string de caracteres não é um formato padrão não ambíguo"

Conseguem me ajudar? Sou novo neste _R world_ rsrs

Obrigado!

**Comment by luisfilipeao** [comment]
Estou tento o mesmo problema, gostaria de entender o motivo. Fiz algus testes e percebi que o carregamento é feito se o argumento do 'information_system' forem os seguintes: SIM-DO | SIM-DOFET | SIM-DOEXT | SIM-DOINF | SIM-DOMAT | SINAN-DENGUE | SINAN-CHIKUNGUNYA | SINAN-ZIKA | SINAN-MALARIA. Para as demais opções, o carregamento retorna este erro que você reportou, mas não sei te dizer o motivo ou como solucionar.

**Comment by edcarllos** [comment]
Boa noite!

Agradecer primeiramente a manutenção do pacote, tem ajudado muito em pesquisas científicas.

Sobre este problema em particular, ainda persiste o erro para diversos sistemas, ao menos para mim. A recuperação de dados para sistemas SIH, SIA e CNES, retornam a saída "Error in charToDate(x)" como relatado na imagem abaixo (tentei especificando a UF nos parâmetros também):

![image](https://github.com/user-attachments/assets/24464c3b-61aa-4c27-8904-098272b99be1)

Já sistemas como SINAN e SINASC estão importando normalmente.

No mais, agradeço a ajuda.
