### ISSUE TITLE
Problema ao processar idade da mãe do SINASC

### ISSUE THREAD

**Issue by davibalves** [rfsaldanha/microdatasus#14]
Ao utilizar a função process_sinasc a variável IDADEMAE mostra uma idade 10 anos mais jovem do que a registrada no sistema, o que não condiz com os arquivos de conversão:

Exemplo: Nascidos Vivos do RJ em 2018:

Antes do Processamento:
> head(nvrj2018$IDADEMAE)
[1] 19 23 15 32 30 43

> summary(as.numeric(as.character(nvrj2018$IDADEMAE)))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  11.00   22.00   27.00   27.18   32.00   99.00

Pós Processamento:
> head(nvrj2018_proc$IDADEMAE)
[1]  9 13  5 22 20 33

> summary(as.numeric(as.character(nvrj2018_proc$IDADEMAE)))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00   12.00   17.00   17.18   22.00   49.00

**Comment by rfsaldanha** [comment]
Obrigado! Vou conferir isso.
