### ISSUE TITLE
CNES - variaveis como factor

### ISSUE THREAD

**Issue by tatillima** [rfsaldanha/microdatasus#15]
Rafael, 

quando eu baixo tabelas do CNES (equipamento - EQ e estabelecimentos - ST), as variáveis estão vindo como fatores. Você sabe como eu posso solucionar isso?

**Comment by rfsaldanha** [comment]
Olá! Isso é algo que eu ainda preciso alterar no pacote, quais são as variáveis?

Temporariamente, você pode rodar o seguinte comando nas variáveis com fator:

dados$VARIAVEL <- as.numeric(levels(dados$VARIAVEL))[dados$VARIAVEL]


Abraços,

Raphael Saldanha

**Comment by tatillima** [comment]
Obrigada, Raphael. Foi isso que acabei fazendo. Da tabela de equipamentos (EQ), são as variáveis:  CNES, CODUFMUN, REGSAUDE, CPF_CNPJ, ATIVIDAD, NATUREZA, TP_UNID, TIPEQUIP, CODEQUIP, IND-SUS, IND_NSUS, COMPETEN e NAT_JUR. E da de estabelecimentos (ST), são as variáveis: CNES, NAT_JUR, TP_UNID, VINC_SUS, COMPETEN.

**Comment by rfsaldanha** [comment]
Corrigido na versão atual do pacote.
