### ISSUE TITLE
NAT_JUR CNES

### ISSUE THREAD

**Issue by rfsaldanha** [rfsaldanha/microdatasus#19]
Estou usando a função fetch_datasus com information_system como CNES-EQ, CNES-LT, CNES-ST e CNES-PF.
De junho de 2012 a maio de 2020, existe um campo NAT-JUR, cujas categorias encontrei em https://github.com/rfsaldanha/microdatasus/wiki/Convenções-SIH-RD.
No entanto, de agosto de 2005 a maio de 2012, o campo NAT_JUR não existe e NATUREZA é definido por categorias (níveis) de 1 a 13.
Encontrei 13 categorias que fazem sentido para o NATUREZA aqui, mas não sei qual corresponde a cada número.
O microdatasus do pacote fornece informações NAT_JUR para os anos de 2005 a 2012? Se sim, onde / como? Ou mesmo se houver uma tabela de correspondência entre NATUREZA e NAT_JUR.

**Comment by beatrizjardim** [comment]
Oi Raphael
Procurando a equivalência, vi que o campo "NATUREZA" diz respeito ao tipo
de prestador no SIASUS.
Fui no DEF e nos CNVs do SIASUS. Encontrei um CNV que eu acredito poder
ajudar. Veja se faz sentido a equivalência que aparece lá.
O arquivo é o ESFERAJUR.CNV e está em
ftp://ftp.datasus.gov.br/dissemin/publicos/SIASUS/200801_/Auxiliar/TAB_SIA.zip

Para complementar:
PORTARIA Nº 1.319, DE 24 DE NOVEMBRO DE 2014

Art. 7º Ficam extintos os campos Esfera Administrativa, Natureza da
Organização, Retenção de Tributos e Tipo de Prestador do CNES.

Parágrafo único. A Coordenação-Geral de Sistemas de Informação do
Departamento de Regulação, Avaliação e Controle de Sistemas deverá
estabelecer critério de equivalência entre a Natureza Jurídica e a Natureza
da Organização para fins de pesquisa e disseminação do CNES em cadastros
anteriores a esta informação.
 AbraSUS

Beatriz

Em sex., 19 de fev. de 2021 às 09:42, Raphael Saldanha <
notifications@github.com> escreveu:

**Comment by rfsaldanha** [comment]
Corrigi com o #33
