### ISSUE TITLE
SIM files before 1996

### ISSUE THREAD

**Issue by oranzani** [rfsaldanha/microdatasus#2]
Raphael,
muito obrigado por construir esse pacote.

Tentei fazer o download de dados do SIM-DO antes de 1996, e ocorre um erro, pois o nome do arquivo/endereço  não existe:
"
(trying URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIM/CID10/DORES/DOAC1979.dbc'
Something went wrong with this URL: ftp://ftp.datasus.gov.br/dissemin/publicos/SIM/CID10/DORES/DOAC1979.dbc
This can be a problem with the Internet or the file does not exist yet.
Error in vars %in% names(partial) : object 'partial' not found
In addition: Warning message:
In download.file(file, temp, mode = "wb") :
  cannot open URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIM/CID10/DORES/DOAC1979.dbc': FTP status was '550 Requested action not taken; file unavailable'"

Acho que é esperado, pois antes de 1996 os dados de causa básica eram codificados em CID9, e estão armazenados em outro diretório e o nome dos arquivos têm a adição de um "R" e os anos estão com 2 dígitos:

SIM/**CID9**/DORES/DO**R**AC**79**.dbc

Espero ter ajudado,
Obrigado,
Otavio

**Comment by fulvionedel** [comment]
Olá Raphael
Antes de tudo, muito obrigado pelo pacote, excelente, super útil!
Aproveito o _issue_ aberto por @oranzani para comentar um problema análogo no SIH: não consigo ler os dados de internação de antes de 2008, porque `fetch_datasus` não os encontra naquela url:

        `tentando a URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/200801_/dados/RDRS0501.dbc'
Something went wrong with this URL: ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/200801_/dados/RDRS0501.dbc
         This can be a problem with the Internet or the file does not exist yet.
         Error in vars %in% names(partial) : objeto 'partial' não encontrado
         Além disso: Warning message:
         In download.file(file, temp, mode = "wb") :
  cannot open URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/200801_/dados/RDRS0501.dbc': FTP status was '550 Requested action not taken; file unavailable'`

Os arquivos DBC já com a CID-10 mas anteriores a 2008 tão no diretório ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/199201_200712/Dados/ 
Se leio com 
`download.file(url="ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/199201_200712/Dados/RDRS0501.dbc", destfile = "RDRS0501.dbc")
aihRS0501 <- read.dbc::read.dbc("RDRS0501.dbc") `
funciona.

Acho que a diferença com o problema abordado por @oranzani é que aqui é apenas de url, não há diferença de CID. Penso que dá pra resolver incluindo um 
`if(year_start < 2008) url <- ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/199201_200712/Dados/ ` 
nos `if(information_system == "SIH ...)`, ou com alguma linha mais acima definindo as url pra cada período.

Grande abraço e mais uma vez obrigado pelo pacote,
Fúlvio
PS: Gostei muito do manual em forma wiki, também :)

**Comment by rfsaldanha** [comment]
@oranzani No desenvolvimento, acabei optando por privilegiar o download e o tratamento dos arquivos de CID-10. Na prática de pesquisa, trabalhar com os arquivos pré-1996 é bem complicado pela qualidade de informação. 

No caso da função `fetch_datasus`, a dificuldade é criar uma lógica que permita o usuário requisitar arquivos dos dois períodos, por exemplo, de 1995 a 2000. Neste caso a função precisa selecionar de acordo com o ano, a URL correta de download.

É plenamente possível fazer, mas acho que não é uma prioridade para o momento. Quero me dedicar mais a tratar os arquivos do CNES agora. Mas de qualquer forma, vamos registrando essas necessidades. Obrigado!

**Comment by rfsaldanha** [comment]
Olá @fulvionedel, a questão é bem parecida com a do @oranzani . Vou precisar refazer a lógica de download para que dê conta de baixar arquivos entre períodos. Obrigado!

**Comment by rfsaldanha** [comment]
Oi pessoal! A atualização recente do pacote (versão 2.0) permite agora o download integrado de dados antigos, atuais e também de versões preliminares.
