### ISSUE TITLE
Download dos dados do SIH-RD antes de 2008 

### ISSUE THREAD

**Issue by heltongraziadei** [rfsaldanha/microdatasus#21]
Olá @rfsaldanha , 

Parabéns pelo pacote! Tentei baixar os dados de hospitalizações da SIH-RD pelo microdatasus e notei que os dados anteriores à 2008 não são baixados pois o padrão da url é diferente para esse período. Deste modo, fiz a seguinte alteração na função fetch_datasus: 

```
else if(information_system == "SIH-RD") {
    if(year_start >= 2008)  url <- "ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/200801_/dados/" 
    else url <- "ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/199201_200712/dados/" 
    files_list <- paste0(url,"RD", file_extension)
}
```

O que viabiliza o download desses dados. Este raciocínio está correto? Aparentemente essa mudança não afeta a função process_sih. 

Obrigado.

**Comment by fulvionedel** [comment]
A sugestão de @heltongraziadei funciona mas (aqui, pelo menos) só quando a lista de anos não compreende os dois períodos. Pra ler arquivos de 2007 a 2008, por exemplo, exige a leitura separada de cada ano, criando dois objetos que devem então ser combinados:
```aihRS0719 <- bind_rows(fetch_datasus(2007, 1, 2007, 12, "RS", "SIH-RD", vars = vars),
                                           fetch_datasus(2008, 1, 2008, 12, "RS", "SIH-RD", vars = vars))
```
Mas se ao criar a sequência de datas for capturado o ano (por exemplo `years <- format(dates, "%Y")`) então a condição funciona mesmo que o período selecionado requeira a leitura das duas url. Mas não consegui que funcionasse por `if()...`, então usei um `ifelse()`.

As alterações foram as seguintes: 
```
# após
dates <- seq(date_start, date_end, by = "month") # linha 67
# incluí
years <- format(dates, "%Y") # find correct url

# chamada das url:
# ...
} else if(information_system == "SIH-RD"){ # linha 133
    url <- ifelse(years < 2008, "ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/199201_200712/dados/", "ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/200801_/dados/" )
    files_list <- paste0(url,"RD", file_extension)
  }
# ...
```

**Comment by ferreirajp** [comment]
Como faço para utilizar a função com esta modificação? Eu precisava baixar os dados anteriores a 2008 mas não consigo.

**Comment by rfsaldanha** [comment]
A atualização recente do pacote (versão 2.0) permite o download de dados anteriores.
