### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by rfgatto** [rfsaldanha/microdatasus#22]
Erro: Failed to install 'microdatasus' from GitHub:
  (convertido do aviso) cannot remove prior installation of package ‘glue’
> library(microdatasus)
Error in library(microdatasus) : 
  there is no package called ‘microdatasus’

**Comment by beatrizmilz** [comment]
Oi @rfgatto ! Não sou mantenedora deste pacote, mas pela minha experiência com esse erro, me parece que deu problema de instalação devido à outro pacote (o glue.. está na mensagem de warning que você colocou).


Tenho uma ideia... segue abaixo um código para realizar os passos:
```
.rs.restartR() # reiniciar o RStudio
remove.packages("glue") # desinstalar o pacote glue
.rs.restartR() # reiniciar o RStudio
install.packages("glue") # instalar novamente o glue
.rs.restartR() # reiniciar o RStudio
devtools::install_github("rfsaldanha/microdatasus") # tentar novamente instalar o microdatasus
```
