### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by samileenf** [rfsaldanha/microdatasus#23]
Olá, encontro este erro ao instalar o microdatasus:
Erro: Failed to install 'microdatasus' from GitHub:
  create process 'C:/R/R-41~1.0/bin/x64/Rcmd.exe' (system error 267, O nome do diretório é inválido.
) @win/processx.c:1040 (processx_exec)

Vocês poderiam me ajudar?

**Comment by rfsaldanha** [comment]
Olá! Fiz diversas alterações e testes recentemente no pacote. Você pode tentar instalar novamente e avisar se deu certo? Obrigado!

**Comment by rfsaldanha** [comment]
Olá! Imagino que esteja tudo certo. Caso tenha alguma dificuldade, posso reabrir a issue.
