### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by ailaviana** [rfsaldanha/microdatasus#24]
Olá!

estou tentando instalar o microdatasus porém aparece o seguinte erro:
Error: Failed to install 'microdatasus' from GitHub:
  create process 'C:/PROGRA~1/R/R-41~1.0/bin/x64/Rcmd.exe' (system error 267, O nome do diretório é inválido.

No Rcloud consigo instalar sem problemas.

**Comment by rfsaldanha** [comment]
Parece ser parecido com o erro da issue #23

**Comment by rfsaldanha** [comment]
Olá! Fiz diversas alterações e testes recentemente no pacote. Você pode tentar instalar novamente e avisar se deu certo? Obrigado!

**Comment by rfsaldanha** [comment]
Olá! Imagino que esteja tudo certo. Caso tenha alguma dificuldade, posso reabrir a issue.

**Comment by ailaviana** [comment]
Bm dia,

Desculpe a demora...só consegui testar esse final de semana. Está tudo ok.
Obrigada pelo retorno.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rfsaldanha** [comment]
Sem problemas!
