### ISSUE TITLE
Sugestões de melhorias para passar no devtools::check()

### ISSUE THREAD

**Issue by beatrizmilz** [rfsaldanha/microdatasus#25]
(anotações da live de 18/08/2021)

- o @rfsaldanha quer submeter ao CRAN, então é importante resolver as questões do `devtools::check()`

Algumas coisas que apareceram no check:

- adicionar `@export` nas funções exportadas, para não precisar alterar o NAMESPACE manualmente

- Caracteres especiais - ASCII

- documentar bases de dados

**Comment by rfsaldanha** [comment]
Feito! Todos os apontamentos do `devtools::check()` foram resolvidos. Apenas ficou uma nota sobre o tamanho de um arquivo. Esse realmente é grande e necessário. Talvez hospedar ele em algum lugar futuramente.
