### ISSUE TITLE
[bug] Erro na instalação do pacote

### ISSUE THREAD

**Issue by filipemsc** [rfsaldanha/microdatasus#29]
Acabei de instalar a nova versão do pacote, utilizando os comandos sugeridos na documentação:
```
install.packages("remotes")
remotes::install_github("rfsaldanha/microdatasus")
```

No entanto, quando vou usar o pacote ele não contém as funções principais (`fetch_datasus` e as funções de processamento).

Por exemplo, quando vou rodar o código sugerido na documentação, ele retorna um erro de que não foi possível encontrar a função `fetch_datasus`

**Traceback:**
```
> library(microdatasus)
> dados <- fetch_datasus(year_start = 2013, year_end = 2014, uf = "RJ", information_system = "SIM-DO")
Error in fetch_datasus(year_start = 2013, year_end = 2014, uf = "RJ",  : 
  não foi possível encontrar a função "fetch_datasus"
```

Quando eu tento ver as funções do pacote, realmente não aparecem essas funções lá:
![bug1](https://user-images.githubusercontent.com/11773789/132013471-d57cb903-d62b-4f3a-b082-2dc83ac0e117.png)
(Não é possível deslizar para baixo, isso é a totalidade de objetos dentro do pacote)

Quando eu tento escrever o "fet..." e clico no tab, para ele autocompletar com "fetch_datasus", também aparece que não há matches
![image](https://user-images.githubusercontent.com/11773789/132013778-a22e705f-5634-4823-9692-fc08d1e3a993.png)

**Comment by rfsaldanha** [comment]
Obrigado por avisar! Não coloquei o `@export` nas funções. Corrigindo isso agora.

**Comment by filipemsc** [comment]
Não faltou colocar um @export?

**Comment by filipemsc** [comment]
Eita! Comentamos na mesma hora :)

**Comment by rfsaldanha** [comment]
Feito! Subi para o `master` agora. Você pode verificar?

**Comment by filipemsc** [comment]
Tudo certo agora! Todas as funções aqui

**Comment by rfsaldanha** [comment]
Ótimo! Obrigado.
