### ISSUE TITLE
Professional CPF number

### ISSUE THREAD

**Issue by aviniciusbb** [rfsaldanha/microdatasus#3]
I've found some issues concerning the variable "CPF_PROF" when reading CNES data. For some reason, the rows came up with encoding issues like in "{}\177\x81\177}\177\x80~}| ". I looked for regex patterns but I couldn't solve this. Please let me know how can I proceed. Thanks in advance.

**Comment by lf-araujo** [comment]
Whenever I need to process these datasets I simply remove this variable, as it causes problems with some packages.

**Comment by bc-teixeira** [comment]
Esse campo usa uma codificação que é nativa do próprio arquivo disponibilizado. Não é necessariamente um problema do pacote.

Esse mesmo padrão está presente em algumas tabelas do SIA para identificação anônima de pacientes. É possível utilizar em sua forma nativa para fazer coortes de pacientes e tudo mais.

Abrindo o arquivo utilizando a codificação ISO-8859-1 você consegue ver esse campo desta forma: "âäâ{{}}ééäÇéää" não agrega grande interpretabilidade, mas presta-se a entender a estrutura.

**Comment by rfsaldanha** [comment]
Vou conferir os arquivos DBF da conversão do DBC, talvez isso esteja acontecendo lá. Se for, não tem muito o que fazer...

**Comment by beatrizjardim** [comment]
O campo é assim mesmo. Ele fica assim por conta do processo de desidentificação feito pelo DATASUS. O mesmo acontece com o Cartão Nacional de Saúde nos arquivos de Radioterapia e Quimioterapia do SIA. Após expandir os aquivos DBC para DBF dentro do próprio TABWIN e na visualização dos DBF dos arquivos, o campo tem essa configuração.
![image](https://user-images.githubusercontent.com/40778212/93616798-943d7180-f9ab-11ea-9892-bfded175b41a.png)

**Comment by rfsaldanha** [comment]
Que legal @beatrizjardim ! Não sabia disso. Estão está confirmado, o dado vem assim mesmo. Nada que possamos fazer.
