### ISSUE TITLE
Função Process_cnes

### ISSUE THREAD

**Issue by jberilo** [rfsaldanha/microdatasus#38]
Boa Tarde Saldanha. 
A função process_cnes não funciona mais? Com posso trazer o nome do estabelecimento de saúde usando as bases do CNES_ST?
Desde já agradecendo.
Att.

**Comment by rfsaldanha** [comment]
Opa! Verifiquei aqui e parece estar funcionando. Após usar a função `process_cnes`, o objeto recebe um campo chamado `FANTASIA` com o nome do estabelecimento.

Qual versão do pacote você está usando? Tente instalar ele novamente e me avise.

**Comment by rfsaldanha** [comment]
Oi @DanielaMayumi conferi agora e estava realmente com um erro. Corrigi com a nova release, 1.4.2. Vou fechar a issue, mas se tiver algo mais relacionado me avise por favor. Muito obrigado!
