### ISSUE TITLE
 Erro durante instalação do pacote: "there is no package called ‘fansi’"

### ISSUE THREAD

**Issue by FabianoMahler** [rfsaldanha/microdatasus#4]
Olá, Raphael! 

Seguindo as etapas para a utilização do microdatasus deparei-me com o seguinte problema:
Primeiro, durante a instalação do pacote o console retorna: 
**Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘fansi’**

Parabéns pelo trabalho!! Peço desculpas caso a questão seja demasiada simples, estou aprendendo R à pouco tempo.

Respeitosamente,
Fabiano Rocha.

**Comment by fulvionedel** [comment]
Olá Fabiano
Como sigo o Raphael neste excelente trabalho e pelo qual  sou muito grato, fui notificado da tua mensagem. Vou meter minha colher, na esperança de que te ajude rapidamente, antes de uma resposta, possivelmente mais adequada, do Raphael.
Tenta instalar antes esse pacote "fansi" a que se refere a mensagem de erro. Talvez um dos pacotes importados pelo microdatasus o necessite. 
abraço
Fúlvio

**Comment by rfsaldanha** [comment]
Olá Fabiano,

Funcionou? Obrigado Fálvio.


Abraços,

Raphael Saldanha

**Comment by rfsaldanha** [comment]
Se o problema persisti, podemos reabrir a issue.
