### ISSUE TITLE
Erro em process_sim() para SIM-DOEXT 2010 e 2011

### ISSUE THREAD

**Issue by MrcLuna** [rfsaldanha/microdatasus#46]
Bom dia. Excelente pacote. 

Durante um processamento de dados do SIM-DOEXT, me deparei com erros na função process_sim(). Ocorre para os anos de 2010 e 2011. Testei no estado CE e MG com mesmo resultado. Segue abaixo cópia do processamento. Entre 2012 e 2019, não ocorre problema. 

`df <- fetch_datasus(year_start = 2010, year_end = 2010, uf = "CE", information_system = "SIM-DOEXT")`
Your local Internet connection seems to be ok.
DataSUS FTP server seems to be up. Starting download...
tentando a URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIM/CID10/DOFET/DOEXT10.dbc'
downloaded 9.4 MB

Warning message:
In utils::download.file(file, temp, mode = "wb") :
  the 'wininet' method is deprecated for ftp:// URLs
`df <- process_sim(df)
`Error in `$<-.data.frame`(`*tmp*`, "NATURAL", value = c(NA, NA, 95L, 83L,  : 
  replacement has 143260 rows, data has 143256_

**Comment by MrcLuna** [comment]
Bom dia, Raphael.  Obrigado pelo retorno rápido. 
Queria esclarecer que o problema não é no download dos dados, mas no processamento feito pelo _**process_sim()**_. Deve haver uma má formação nos dados de 2010 e 2011 que gera algum erro retornando:
```
Error in `$<-.data.frame`(`*tmp*`, "NATURAL", value = c(NA, NA, 95L, 83L,  : 
  replacement has 143260 rows, data has 143256
```
No caso, com o erro, não ocorre o tratamento dos campos dos dados, permanecendo como baixado. 

Obrigado.

**Comment by rfsaldanha** [comment]
Olá! Realmente, consegui reproduzir o problema agora. A função `process_sim()` trabalha, por enquanto, apenas com os dados do SIM-DO. Não tive tempo para estender a função para as outras variações do SIM (DOFET, DOEXT etc).

**Comment by MrcLuna** [comment]
Ah, OK. 
De qualquer forma, obrigado.
