### ISSUE TITLE
MISSING SIH SP 2020 06-12

### ISSUE THREAD

**Issue by Ivnstts** [rfsaldanha/microdatasus#47]
Oi Rafael!
Parabéns pelo pacote, ele é incrível e muito completo.

Notei que após o apagão de dados não consigo exportar mais esse período para o estado de SP. Esse erro ocorre para vc também?

Obrigado pela atenção.

**Comment by rfsaldanha** [comment]
Oi Ivan, obrigado!

Vou verificar. Qual é o período que você não está conseguindo?

**Comment by Ivnstts** [comment]
Obrigado Rafael !
Eu fiz pelo método mensal, de exportar todos os estados ao mesmo tempo.

Vc acha que devo trocar para exportar de estado em estado ?

Que bom que foi uma mera flutuação do sistema.

Grande abraço

Em qui., 17 de fev. de 2022 10:02, Raphael Saldanha <
***@***.***> escreveu:

**Comment by rfsaldanha** [comment]
Isso vai depender mais da quantidade de dados que você está baixando, da memória do seu PC e da estabilidade da internet. Pessoalmente, para o SIH, prefiro baixar 1 ano para todos os estados, e juntar depois se necessário.

**Comment by Ivnstts** [comment]
Obrigado rafa !

Em seg., 21 de fev. de 2022 07:45, Raphael Saldanha <
***@***.***> escreveu:
