### ISSUE TITLE
Download dos dados SINASC 

### ISSUE THREAD

**Issue by 20elleirbag** [rfsaldanha/microdatasus#48]

**Comment by rfsaldanha** [comment]
Opa, bom dia! A sua mensagem não aparece no GitHub mas veio completa por email. O problema de baixar os dados de MG de 2019 persiste?

**Comment by 20elleirbag** [comment]
Eu consegui arrumar, não era problema com os dados. Eu estava com uma das
funções desatualizadas.

Obrigada pela atenção
