### ISSUE TITLE
FTP datasus SIA-PA uf=SP, arquivos com 9 dígitos

### ISSUE THREAD

**Issue by caio-peixoto** [rfsaldanha/microdatasus#5]
nome arquivos .dbc no ftp datasus SIA-PA para São Paulo tem 9 dígitos...
SIA-PA dbc para São Paulo são do tipo:
**PASP1712a.dbc
PASP1712b.dbc**

etc... -> função 'microdatasus::fetch_datasus' não funciona nesse caso..

ftp://datasus.gov.br/dissemin/publicos/SIASUS/200801_/Dados

**Comment by rfsaldanha** [comment]
Oi Caio,

Corrigi agora esse bug. Pode atualizar o pacote e testar. Abraços!
