### ISSUE TITLE
[sugestão/feature] Função para obter dicionário de procedimentos

### ISSUE THREAD

**Issue by filipemsc** [rfsaldanha/microdatasus#54]
Na minha opinião, uma das partes mais difíceis de analisar dados do SIA/SIH é identificar quais os códigos dos procedimentos de interesse.

Minha sugestão é ter uma função no pacote que retorne uma tabela com os respectivos códigos de procedimento + nome do procedimento + ano/mês em que os procedimentos estão disponíveis. Acho importante ter essa última informação uma vez que procedimentos muitas vezes são extintos ou criados ao longo do tempo.  

A minha dúvida é se a melhor forma de fazer isso é simplesmente upando essa base no Github mensalmente, ou se criando uma função que faz o download de arquivos do FTP do Datasus e cria essa base.

Mas, para exemplificar como isso poderia ser feito a partir de código, dou um exemplo abaixo:

```r
get_proc = function(file){
  txt = read.delim(unzip(file, "tb_procedimento.txt"), header = FALSE)
  
  id_proc = purrr::as_vector(substring(purrr::as_vector(txt),1,10))
  proc = purrr::as_vector(substring(purrr::as_vector(txt), first= 11,last = 260))
  
  data.frame(id_proc, proc)
}

link <- "ftp://ftp2.datasus.gov.br/pub/sistemas/tup/downloads/"

arqs <- RCurl::getURLContent(link)

temp_names <- stringr::str_extract_all(arqs,"TabelaUnificada.*zip")[[1]]

links <- paste0(link,temp_names)

data <- NULL

for(link in links){
  
  yearmo <- stringr::str_extract(link, "_([0-9]+)") |> stringr::str_remove("_")
  temp <- tempfile()
  
  utils::download.file(link, temp, mode = "wb")
  partial <- get_proc(temp)
  partial <- cbind(yearmo, partial)
  data <- dplyr::bind_rows(data, partial)
  unlink(temp)
}

dicionario <- data |>
  dplyr::group_by(id_proc) |>
  dplyr::summarise(proc = dplyr::first(proc), yearmo = paste(yearmo, collapse=","))
```
Se não tiver nenhum erro, este código deve retornar uma base conforme descrevi anteriormente. Assim:
![image](https://user-images.githubusercontent.com/11773789/177012592-be834da4-a8a8-499c-8214-0794bbec61b5.png)
Note que alguns procedimentos foram criados ao longo do tempo. 

Se quiser posso escrever como uma função exportável e abrir um PR. Esse é só um rascunho que fiz mesmo.

**Comment by filipemsc** [comment]
Outra opção seria incorporar essa funcionalidade nas funções `process_sia` ou `process_sih`.  Eu acho que a minha sugestão é melhor porque:
1) Essas bases já são bem grandes, colocar uma coluna que tem strings muito longas pode torná-las ainda maiores.
2) Uma pessoa que for fazer uma análise dos procedimentos sem saber que ele foi descontinuado pode ser induzida ao erro de achar que ele deixou de ser realizado.

**Comment by rfsaldanha** [comment]
Resolvido na função `process_sia`. Caso o argumento `nome_proced` seja `TRUE`, o dicionário mais recente será baixado do DataSUS.
