### ISSUE TITLE
``process_sim(.)`` pra 2010 quebrado

### ISSUE THREAD

**Issue by lucasccdias** [rfsaldanha/microdatasus#55]
Não sei se isso acontece também para outros anos (tentei só 2000 e 2010, pra 2000 funcionou normalmente). Aqui está como reproduzir o erro:

```r
remotes::install_github("rfsaldanha/microdatasus")
library(microdatasus)

data_10 = fetch_datasus(year_start = 2010, year_end = 2010, information_system = "SIM-DO")
data_10 = process_sim(data_10)

Error in `$<-.data.frame`(`*tmp*`, "NATURAL", value = c(126L, 2L, 2L,  : 
  replacement has 1136968 rows, data has 1136947
```

**Comment by rfsaldanha** [comment]
Olá!

Testei agora o mesmo código e ele funcionou. Talvez o DataSUS tenha alterado os arquivos e corrigido algo. De qualquer forma, quando isso acontece, recomendo que baixe e processe cada ano separadamente para poder isolar o problema.
