### ISSUE TITLE
[erro/bug] lista de etnias nas funções de processamento

### ISSUE THREAD

**Issue by filipemsc** [rfsaldanha/microdatasus#57]
As funções de processamento consideram que a variável de etnia é numérica, indo de 1 a 264. Em algumas bases, entretanto, percebi que existiam etnias "X265", "X266", etc. Achei estranho, visto que os CNV de dicionário realmente só catalogam as etnias de 1 a 264. No entanto, acho que existem evidências de que essas entradas não configuram erro, e sim alguma atualização na base de etnias do SUS, conforme pode ser visto neste site:

https://integracao.esusab.ufsc.br/ledi/documentacao/referencias/dicionario.html

Minha sugestão, por ora: não classificar esses códigos como nulos, como faz o código atual, por provavelmente não serem casos nulos de fato.

**Comment by rfsaldanha** [comment]
Oi Filipe, obrigado pela contribuição. Estou de acordo, essa tabela vai ajudar a complementar a lista de etnias que está nas funções de pré-processamento. 

Preciso agora atualizar essa parte do código, complementando esses códigos. Toda ajuda é bem vinda!

**Comment by rfsaldanha** [comment]
Obrigado pelo Pull Request!! Acabei de aceitar ele.
