### ISSUE TITLE
Código dos municípios incompativel com IBGE

### ISSUE THREAD

**Issue by mixedlogit** [rfsaldanha/microdatasus#59]
Olá,

Estou fazendo download de dados do SIM-DOEXT para o estado de SC entre 2010 e 2020. Estou tentando fazer um left_join a partir dos dados do pacote geobr. Aparentemente os códigos de municipio para o Estado de SC não são os mesmos que os códigos do IBGE. Alguém sabe qual poderia ser o problema? Valeu!

**Comment by filipemsc** [comment]
@gacaldeira os códigos do `geobr` são aqueles fornecidos pelo IBGE, de 7 dígitos. O padrão do SUS é utilizar códigos de 6 dígitos. Você pode encontrar a equivalência entre os dois códigos aqui:
https://basedosdados.org/dataset/br-bd-diretorios-brasil?bdm_table=municipio

**Comment by rfsaldanha** [comment]
Olá,

Os códigos de municípios utilizados pelo DataSUS equivalem aos códigos do IBGE até o sexto dígito, onde são truncados.
