### ISSUE TITLE
Erro no Download dos dados

### ISSUE THREAD

**Issue by DacolGiovani** [rfsaldanha/microdatasus#60]
Na atualização do R da versão 4.1.1 o method padrão para ‘⁠ftp://⁠’ URIs foi depreciado. 

Com isso o ocorre o erro: 
"Something went wrong with this URL: ...
This can be a problem with the Internet or the file does not exist yet."

Esse erro pode ser corrigido inserindo o parametro "method = "libcurl"" na linha de download dos dados.

**Comment by rfsaldanha** [comment]
Obrigado por avisar!! Vou testar a correção e atualizar o pacote.
