### ISSUE TITLE
Código CNES 

### ISSUE THREAD

**Issue by alinesfv** [rfsaldanha/microdatasus#62]
Olá! Boa tarde!
Tenho usado muito o microdatasus! Que pacote maravilhoso! Obrigada
No momento, baixando os dados do CNES - "CNES-ST"e ao fazer o processamento usando o process_cnes chego em um problema envolvendo o código dos estabelecimentos.
Quando há zeros à esquerda no código CNES o processamento não é feito de maneira adequada e surgem muitos NAs no banco. 
Há como resolver esse problema?
Grata, Rafael!

**Comment by rfsaldanha** [comment]
Olá! Obrigado, fico feliz em saber que o pacote está sendo útil.

Tenho a impressão de ter corrigido isso a algum tempo... o problema persiste? Você consegue me enviar um exemplo de quando isso ocorre?
