### ISSUE TITLE
fetch_datasus CNES baixa somente um estado, na opção uf="all"

### ISSUE THREAD

**Issue by fabionogu** [rfsaldanha/microdatasus#63]
Boa Noite,

O arquivo fetch_datasus não está baixando os demais arquivos da base CNES independente de ser ST, PF, LT ou EQ, quando a opção de todos os estados é selecionada. 
por Exemplo:
df.CNES.LT <- fetch_datasus(year_start = 2022,month_start=10,month_end = 10,
                            year_end = 2022, uf="all", information_system = "CNES-LT")

**Comment by rfsaldanha** [comment]
Prezados, consegui corrigir o problema agora. Peço que instalem novamente o pacote e testem.
