### ISSUE TITLE
Erro de instalação

### ISSUE THREAD

**Issue by vitor-benfica** [rfsaldanha/microdatasus#65]
remotes::install_github("rfsaldanha/microdatasus")

Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2023-03-11 23:32:28 UTC

Como posso resolver isso?

**Comment by fulvionedel** [comment]
Olá @vitor-benfica 

Isso acontece comigo porque tenho uma conta no GitHub e uma vez peguei a identificação (acho que um token, não lembro :B) no perfil do R, pra que pudesse subir minhas coisas sem ter de inserir senha a cada vez. Mas depois disso, cada vez que quero instalar um pacote de terceiros do GitHub, preciso primeiro anular isso.
Procura enviar antes o seguinte comando: `Sys.unsetenv("GITHUB_PAT")` e depois o `remotes::install_github("rfsaldanha/microdatasus")`.

Espero que ajude. :)

**Comment by vitor-benfica** [comment]
Obrigado @fulvionedel, era isso mesmo, algum tolken de acesso melando o rolê, problema resolvido!
