### ISSUE TITLE
Download File Timeout

### ISSUE THREAD

**Issue by BrunBP** [rfsaldanha/microdatasus#66]
Estou tentando baixar dados do SIA-PA, porém a todo momento os erros abaixo são reportados:

_1: In utils::download.file(file, temp, mode = "wb", method = "libcurl") :
  downloaded length 15526138 != reported length 116580110
2: In utils::download.file(file, temp, mode = "wb", method = "libcurl") :
  URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIASUS/200801_/Dados/PAPR2211.dbc': Timeout of 60 seconds was reached_

Acredito que o problema seja apenas a questão do TIMEOUT, visto que conseguido baixar outros arquivos menores, como o SIH-SP.
De acordo com a pagina do pacote "Download File", tem como definir um tempo para TIMEOUT e o padrão é definido em 60 segundos.

_The timeout for many parts of the transfer can be set by the option timeout which defaults to 60 seconds. This is often insufficient for downloads of large files (50MB or more) and so should be increased when download.file is used in packages to do so. Note that the user can set the default timeout by the environment variable R_DEFAULT_INTERNET_TIMEOUT in recent versions of R, so to ensure that this is not decreased packages should use something like_

    options(timeout = max(300, getOption("timeout")))

**Comment by renanaltrao** [comment]
> Olá! Nesse caso, você pode definir esta opção antes de iniciar o download, sem necessidade de alterar a função interna do pacote.

Sugiro adicionar um observação no readme sobre os arquivos do SIA-PA sobre a possível necessidade de aumentar o timeout antes do download
