### ISSUE TITLE
Health informaton system unknown for SINAN-DENGUE-FINAL/PRELIMINAR

### ISSUE THREAD

**Issue by denisecammarota** [rfsaldanha/microdatasus#67]
Olá! 
Estava tentando baixar os dados de casos da dengue usando 'SINAN-DENGUE-FINAL'  e 'SINAN-DENGUE-PRELIMINAR' como information_system na função fetch datasus. Porém, tive o seguinte erro: 'Health information system unknown.'. Os dois aparecem como sistemas implementados na descrição ao inicio do arquivo da função.
Esse é o código que estava usando: 
`dengue_list <-fetch_datasus(year_start = 2020, year_end = 2021, information_system = 'SINAN-DENGUE-FINAL')`
Parece funcionar usando o argumento ‘SINAN-DENGUE’, mas não sei se tem alguma diferença com os dados com esses argumentos. 
Desde já, muito obrigada pela sua atenção e pelo maravilhoso pacote.
Denise.

**Comment by rfsaldanha** [comment]
Olá! Em uma das atualizações do pacote, eu juntei essas opções para não ser mais necessário especificar se é final ou preliminar. Pode usar como argumento o `SINAN-DENGUE`.
