### ISSUE TITLE
Problemas na instalação do pacote

### ISSUE THREAD

**Issue by guicastrol** [rfsaldanha/microdatasus#68]
Olá meus caros,

Estou tendo problemas na instalação do pacote.

`> remotes::install_github("rfsaldanha/microdatasus")
Downloading GitHub repo rfsaldanha/microdatasus@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/rfsaldanha/microdatasus/tarball/HEAD'`

Alguma ideia ?

**Comment by GleytonLima** [comment]
O mesmo aqui. Talvez esteja relacionado com o fato do pacote read.dbc ter sido arquivado por "violação de política":
![image](https://user-images.githubusercontent.com/8837535/232174340-e388cd77-4188-4dc6-93a0-18d440a9cc53.png)
https://cran.r-project.org/web/packages/read.dbc/index.html

**Comment by rfsaldanha** [comment]
Opa! Não sabia dessa situação com o {read.dbc}. Uma alternativa é instalar a versão de desenvolvimento dele e depois instalar o {microdatasus}

`remotes::install_github("danicat/read.dbc")`

**Comment by rfsaldanha** [comment]
Vou tentar colocar a dependência do {read.dbc} de desenvolvimento no {microdatasus}.

**Comment by brunnohs** [comment]
Estou com problemas na instalação do pacote:

remotes::install_github("rfsaldanha/microdatasus")

Downloading GitHub repo rfsaldanha/microdatasus@HEAD
Downloading GitHub repo danicat/read.dbc@HEAD
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\brunnohs.TCE-RS\AppData\Local\Temp\RtmpcpMbdo\remotesfa470f0247c\danicat-read.dbc-eb654e5/DESCRIPTION' (702ms)
─  preparing 'read.dbc': (586ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'read.dbc_1.0.5.tar.gz'
   
Installing package into ‘C:/Users/brunnohs.TCE-RS/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'read.dbc' ...
** using staged installation
** libs
gcc  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c blast.c -o blast.o
/bin/sh: line 1: gcc: command not found
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:253: blast.o] Error 127
ERROR: compilation failed for package 'read.dbc'
* removing 'C:/Users/brunnohs.TCE-RS/AppData/Local/R/win-library/4.2/read.dbc'
Downloading GitHub repo danicat/read.dbc@HEAD
Skipping read.dbc, it is already being installed
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\brunnohs.TCE-RS\AppData\Local\Temp\RtmpcpMbdo\remotesfa431ca436d\rfsaldanha-microdatasus-0967679/DESCRIPTION' (454ms)
─  preparing 'microdatasus': (1.4s)
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts (342ms)
─  checking for empty or unneeded directories
─  building 'microdatasus_2.1.1.tar.gz'
   
Installing package into ‘C:/Users/brunnohs.TCE-RS/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
ERROR: dependency 'read.dbc' is not available for package 'microdatasus'
* removing 'C:/Users/brunnohs.TCE-RS/AppData/Local/R/win-library/4.2/microdatasus'
Warning messages:
1: In i.p(...) :
  installation of package ‘C:/Users/BRUNNO~1.TCE/AppData/Local/Temp/RtmpcpMbdo/filefa423b638e8/read.dbc_1.0.5.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘C:/Users/BRUNNO~1.TCE/AppData/Local/Temp/RtmpcpMbdo/filefa46a71a8b/microdatasus_2.1.1.tar.gz’ had non-zero exit status


Alguem pode ajudar?

**Comment by rfsaldanha** [comment]
Prezados, o pacote `read.dbc` da Daniela Petruzalek voltou para o CRAN. Acho que os problemas de instalação que afetam o `microdatasus` foram resolvidos.

**Comment by schatz-mann** [comment]
Acho que voltou a dar o mesmo problema...
