### ISSUE TITLE
Problema com encoding no SINAN-CHIKUNGUNYA  em 2021

### ISSUE THREAD

**Issue by tonyarauj0** [rfsaldanha/microdatasus#69]
Olá.
Baixando os dados do SINAN-CHIKUNGUNYA  , para 2021, algumas colunas aparecem com erro de encoding a partir de CS_SEXO. Com isso, não dá pra utilizar a função process_sinan_chikungunya.
Obrigado!

**Comment by rfsaldanha** [comment]
Olá! Parece ser um problema nos arquivos que vem do DataSUS. Uma opção seria aplicar a função `enc2utf8` nas colunas antes de processá-las.
