### ISSUE TITLE
Issue with the function `process_cnes_st`

### ISSUE THREAD

**Issue by jocamarada** [rfsaldanha/microdatasus#7]
Using the code below you cannot process the dataset with the function `process_cnes_st`

```
    CNES_ST_m <- fetch_datasus(year_start = 2019, 
                                year_end = 2019,
                                month_start = 1,
                                month_end = 1,
                                information_system = "CNES-ST")
    
    CNES_ST_BR_m = process_cnes_st(CNES_ST_m, municipality_data = T)
```

The code results in the following error: 

```
Error in dplyr::left_join(data, cadger, by = c(CNES = "CNES")) : 
  object 'cadger' not found
```

**Comment by caio-peixoto** [comment]
just comment lines 30:32 of  microdatasus/R/process_cnes_st.R file.

also, try to load all needed variables with:
load("./microdatasus/data/cbo02.RData")
load("./microdatasus/data/vinculo.RData")
load("./microdatasus/R/sysdata.rda")

**Comment by rfsaldanha** [comment]
This was a problem when I committed the package, some files were accidentally removed. This is resolved now.
