### ISSUE TITLE
Melhorar eficiencia da função process_cnes()

### ISSUE THREAD

**Issue by rafapereirabr** [rfsaldanha/microdatasus#74]
Oi Rafael.  Notei que a função `process_cnes()` está toda escrita em base R, o que deixa o codigo bem lento, especial no caso de bases com muitas observações. Eu vetorizei várias operações e traduzi o script para sintaxe do `data.tabe`, de maneira que o script ficou beeem mais eficiente.

Num teste rápido aqui para uma base pequena (um mês de "CNES-PF" de Roraima), a função atual demora cerca de 15 segundos, e a versão com `data.table` demora cerca de 1 segundo.  Para bases maiores, essa diferença tende a ser ainda maior.

Boa parte das alterações que fiz poderiam ser aproveitadas para melhorar as demais funções `process_` sem muito esforço.

Se você tiver interesse, eu posso detalhar melhor essa comparação acima, e fazer um pull request. Sei que manutenção de pacote dá um baita trabalho e tem suas idiosincrasias. Então fique a vontade para recusar a sugestão ou responder quando puder.

**Comment by rfsaldanha** [comment]
Olá Rafael,

Perfeito! Tenho vontade de refatorar todo o pacote, usando `dplyr` ou `dtplyr` (que usa internamente o `data.table`), para deixar o código melhor, mais bem escrito e mais eficiente.

O tempo está curto para fazer isso agora, mas toda ajuda é bem-vinda.

**Comment by rafapereirabr** [comment]
outro ponto é que eu reduzi muito a redundância do código. O script original tinha quase 1800 linhas. A versão revisada com data.table tem 564 linhas. Para isso eu precisei criar algumas funções internas do pacote para conversao das classes das colunas.

**Comment by rfsaldanha** [comment]
Cara, isso é fantástico! Se já estiver maduro, faz um pull request e podemos fazer refatoração começando pelo CNES. Depois, vou refatorando as outras funções aprendendo com a sua. Muito obrigado!

**Comment by rfsaldanha** [comment]
Olá Rafael, aprovei o pull request agora. Obrigado!
