### ISSUE TITLE
fetch_datasus problem with multiple UFs

### ISSUE THREAD

**Issue by oranzani** [rfsaldanha/microdatasus#77]
Oi @rfsaldanha , hoje brincando com download do SIH, usando a função `fetch_datasus` para mais de uma UF, sempre recebi o seguinte erro:

`Error in if (information_system %in% sisSINAN & uf != "all") { : 
  the condition has length > 1`

```
    if (information_system %in% sisSINAN & uf != "all") {
        message("SINAN files are not available per UF. Ignoring argument 'uf' and downloading all data.")
    }
```

https://github.com/rfsaldanha/microdatasus/blob/f0fda7a36cfcb294251b720699fecd14bfdf3d12/R/fetch_datasus.R#L84C2-L84C2

Imagino que precise de um if else.

Valeu

**Comment by rfsaldanha** [comment]
Obrigado! Consegui arrumar agora.
