### ISSUE TITLE
Falta de atualização do SIGTAP

### ISSUE THREAD

**Issue by filipemsc** [rfsaldanha/microdatasus#79]
O pacote tem uma função que retorna a tabela de procedimentos SIGTAP. Atualmente, a tabela está salva como um .rda que não é atualizado há mais de 2 anos. O problema é que essa tabela é dinâmica e atualizada mês a mês. 

Ideia: criar uma função que leia a tabela para um determinado mês/ano solicitado.

Posso fazer um PR para ajudar?

**Comment by rfsaldanha** [comment]
Opa, ótima ideia! Pode fazer o PR, vai ajudar muito.

**Comment by rfsaldanha** [comment]
Fiz a alteração na função para baixar a tabela atualizadaa. Disponível na v2.2.3.
