### ISSUE TITLE
NAT_JUR missing field for early years

### ISSUE THREAD

**Issue by hsvab** [rfsaldanha/microdatasus#8]
I am using fetch_datasus function with information_system as CNES-EQ, CNES-LT, CNES-ST and CNES-PF.

From June 2012 to May 2020 there is a field NAT-JUR, whose categories I found at https://github.com/rfsaldanha/microdatasus/wiki/Convenções-SIH-RD.

However, from August 2005 to May 2012 the field NAT_JUR does not exist and NATUREZA is defined by categories (levels) from 1 to 13.
I found 13 categories that make sense to NATUREZA [here](http://tabnet.datasus.gov.br/cgi/cnes/naturezaorganização.htm), but I don't know which one matches each number.

Does the package microdatasus deliver NAT_JUR information for years 2005-2012? If so, where/how?
Or even if there is a correspondence table between NATUREZA and NAT_JUR.

**Comment by rfsaldanha** [comment]
Thanks! I will take a look on that.

**Comment by rfsaldanha** [comment]
Bug corrected with #33
