### ISSUE TITLE
 Erro: Can't join `x$MUNIC_RES` with `y$MUNIC_RES` due to incompatible types

### ISSUE THREAD

**Issue by ptachi** [rfsaldanha/microdatasus#81]
Boa tarde! Em primeiro lugar, muitíssimo obrigada pela criação do pacote!

Eu estou trabalhando com dados do SIH_RD e quando uso a função process_sih recebo a seguinte mensagem de erro: 

Error in `dplyr::left_join()`:
! Can't join `x$MUNIC_RES` with `y$MUNIC_RES` due to incompatible types.
ℹ `x$MUNIC_RES` is a <character>.
ℹ `y$MUNIC_RES` is a <integer>.

Tentei com outras conformações de datas/UFs, mas todas deram este erro. Um exemplo que resultou neste erro:

dados <- fetch_datasus(year_start = 2022, year_end = 2022, month_start= 1, month_end=2, uf = "SP", information_system = "SIH-RD")
dadosproc <- process_sih(dados)

Desde já agradeço a atenção.

**Comment by rfsaldanha** [comment]
Olá! Obrogado por avisar. Corrigi o pacote e a versão atual não tem mais esse problema.
