### ISSUE TITLE
Erro no process_cnes - CNES-PF

### ISSUE THREAD

**Issue by renanaltrao** [rfsaldanha/microdatasus#82]
Olá, 

Não estou conseguindo realizar o process CNES no CNES-PF. Ocorre o seguinte erro:

```
> dados <- fetch_datasus(year_start = 2023,month_start = 05,year_end = 2023,month_end = 05,uf = "SC",information_system = "CNES-PF")
Your local Internet connection seems to be ok.
DataSUS FTP server seems to be up. Starting download...
trying URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/CNES/200508_/Dados/PF/PFSC2305.dbc'
Content type 'unknown' length 11548847 bytes (11.0 MB)
> dados <- process_cnes(data = dados, information_system = "CNES-PF")
Error in eval(jsub, SDenv, parent.frame()) : 
  invalid multibyte string at '<aa>'
```

Tentei atualizar o pacote, mas já está na versão mais recente.

**Comment by rfsaldanha** [comment]
Olá! Conferi a situação, o DataSUS está criando alguns arquivos com problema de codificação, colocando strings em variáveis que deveriam ser numéricas. Alterei o código para lidar com essa situação. A versão mais atual do pacote lida com esse problema.
