### ISSUE TITLE
Error in process_sih()

### ISSUE THREAD

**Issue by rafapereirabr** [rfsaldanha/microdatasus#88]
# reprex
```
library(microdatasus)

inter <- fetch_datasus(year_start = 2018, month_start = 1, 
                       year_end = 2018, month_end = 3,
                       uf = "RJ",
                       information_system = "SIH-RD")

inter_m <- process_sih(inter, municipality_data = TRUE)
```

The code above returns the following error:

> Error in `dplyr::left_join()`:
>   ! Can't join `x$MUNIC_RES` with `y$MUNIC_RES` due to incompatible types.
> ℹ `x$MUNIC_RES` is a <character>.
> ℹ `y$MUNIC_RES` is a <integer>.
> Run `rlang::last_trace()` to see where the error occurred.
>

**Comment by rfsaldanha** [comment]
Hi Rafael! I couldn't reproduce the error with the reprex, it runs smoothly. Can you confirm it?

**Comment by rafapereirabr** [comment]
Hi @rfsaldanha . I'm now getting another error before that one:
> Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to ftp.datasus.gov.br port 21: Timed out

If you plan to put the package on CRAN, mind you that this kind of error is not accepted by CRAN policies. They require that functions 'fail gracefuly' in case on problems with internet connection. This means that in such cases, the function should not throw and error. It should return `NULL` with an informative message
