### ISSUE TITLE
Inconsistência nos códigos municipais na tabela DO-EXT

### ISSUE THREAD

**Issue by brunopantaleao** [rfsaldanha/microdatasus#89]
Prezados
Até o ano 2005 os códigos de município de residência e de ocorrência contém 7 dígitos.
A partir do ano 2006, os dados são baixadas contendo 6 dígitos.
Atenciosamente,

**Comment by rfsaldanha** [comment]
Olá Bruno, obrigado por avisar. Por essa eu não esperava. Realmente, as variáveis estão assim no DataSUS. Vou incluir um passo na `process_sim` para truncar o sétimo dígito.
