### ISSUE TITLE
Erro em process_sim()

### ISSUE THREAD

**Issue by helkennedy** [rfsaldanha/microdatasus#95]
Na função process_sim() há um erro no processamento do código de residência. Não é possível fazer o merge de data e tabMun. A linha `else if ("CODMUNRES" %in% variables_names & municipality_data == TRUE)` nunca é rodada porque a condição anterior `("CODMUNRES" %in% variables_names)` é sempre verdadeira.

```
if ("CODMUNRES" %in% variables_names) {
    if (nchar(data$CODMUNRES[1]) == 7) {
      data$CODMUNRES <- substr(data$CODMUNRES, 0, 6)
    }
  }
  else if ("CODMUNRES" %in% variables_names & municipality_data == TRUE) {
    colnames(tabMun)[1] <- "CODMUNRES"
    tabMun$CODMUNRES <- as.character(tabMun$CODMUNRES)
    data <- dplyr::left_join(data, tabMun, by = "CODMUNRES")
}
```

Uma opção de correção seria colocar o bloco` if ("CODMUNRES" %in% variables_names & municipality_data == TRUE)` em um if separado.

```
if ("CODMUNRES" %in% variables_names){
    if(nchar(data$CODMUNRES[1]) == 7){
      data$CODMUNRES <- substr(data$CODMUNRES, 0, 6)
    }
  } 
if ("CODMUNRES" %in% variables_names & municipality_data == TRUE) {
    colnames(tabMun)[1] <- "CODMUNRES"
    tabMun$CODMUNRES <- as.character(tabMun$CODMUNRES)
    data <- dplyr::left_join(data, tabMun, by = "CODMUNRES")
  }
```

**Comment by rfsaldanha** [comment]
Olá! Acho que resolvi esse problema na versão mais recente. Caso ainda ocorra o erro, pode me procurar.
