### ISSUE TITLE
[fetch_datasus, SIM-DO] Diferença entre o total de óbitos utilizando uf = "all"

### ISSUE THREAD

**Issue by jvalopes** [rfsaldanha/microdatasus#97]
Oi, @rfsaldanha! Tudo bem?

Quando utilizei a função abaixo encontrei um total de 17.366.551 óbitos. Mas quando apliquei essa mesma função separadamente para cada uf, obtive 17.412.995. Ao conferir os dados com as tabelas geradas pelo tabnet também encontrei 17.412.995. Então, a princípio acredito que possa ter ocorrido algum problema no download dos .dbc, ou algum erro com a opção uf = "all".

`df <- fetch_datasus(year_start = 2010,
                    month_start = 1,
                    year_end = 2022,
                    month_end = 12,
                    uf = "all",
                    information_system = "SIM-DO")`

**Comment by gustavoalcantara** [comment]
Fala @jvalopes, se possível, rode o `rlang::last_trace()` pra gente conseguir ver o flow

**Comment by oranzani** [comment]
Eu acho que o problema pode ser que no "all" ele encontrou problema em alguma UF/mes e não baixou. Eu às vezes tenho este problema. Algo bom para o microdatasus seria um summary do que foi baixado ou não, em termos de mês e local. Pensei em como fazer isso, mas ainda não evoluí. valeu!

**Comment by oranzani** [comment]
Olá, @rfsaldanha, eu adicionei essa linha no código para gerar no dataframe final da onde o arquivo veio

`partial$source <- substr(file,nchar(url)+1,nchar(file)-4)`, 

depois `partial <- read.dbc::read.dbc(temp, as.is = TRUE)` 

na função `fetch_datasus`

Assim ele adiciona. Não sei se essa solução estaria de acordo com os princípios do pacote. Ou se seria melhor coletar onde teve problema e retornar um vector/df com os mesmos.
Espero ter ajudado algo,
Abraço

**Comment by rfsaldanha** [comment]
Opa! Interessante, vou incorporar como opcional na função. Obrigado!

**Comment by rfsaldanha** [comment]
Resolvido com o argumento `track_source` na função `fetch_datasus`.
