### ISSUE TITLE
erro na instalação

### ISSUE THREAD

**Issue by calvetufma** [rfsaldanha/microdatasus#99]
obtive o seguinte erro ao tentar instalar usando os comandos da documentação
> # install.packages("remotes")
> remotes::install_github("rfsaldanha/microdatasus")

Erro:

Downloading GitHub repo rfsaldanha/microdatasus@HEAD
Downloading GitHub repo danicat/read.dbc@HEAD
Erro: Failed to install 'microdatasus' from GitHub:
  Failed to install 'read.dbc' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

**Comment by rfsaldanha** [comment]
Olá! Você tentou fazer a instalação em qual sistema operacional e versão do R?

**Comment by calvetufma** [comment]
Windows 10

Mas já consegui desenrolar, achei um tutorial no YouTube usando R Studio.
Obrigado.

Em qui., 4 de abr. de 2024 10:22, Raphael Saldanha ***@***.***>
escreveu:

**Comment by rfsaldanha** [comment]
Que bom!
